# Generated by Django 5.1 on 2024-08-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=70)),
                ("description", models.CharField(max_length=100)),
                ("prix", models.CharField(max_length=20)),
                ("nombre", models.IntegerField(max_length=20)),
            ],
        ),
    ]
