# Generated by Django 5.1 on 2024-08-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="nombre",
            field=models.IntegerField(),
        ),
    ]
